//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DdsFileTypePlus.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DdsFileTypePlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC6H / BC7 Compression Speed.
        /// </summary>
        internal static string BC7CompressionSpeed_DisplayName {
            get {
                return ResourceManager.GetString("BC7CompressionSpeed_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fast.
        /// </summary>
        internal static string BC7CompressionSpeed_Fast {
            get {
                return ResourceManager.GetString("BC7CompressionSpeed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium.
        /// </summary>
        internal static string BC7CompressionSpeed_Medium {
            get {
                return ResourceManager.GetString("BC7CompressionSpeed_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slow.
        /// </summary>
        internal static string BC7CompressionSpeed_Slow {
            get {
                return ResourceManager.GetString("BC7CompressionSpeed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cube Map from crossed image.
        /// </summary>
        internal static string CubeMap_Description {
            get {
                return ResourceManager.GetString("CubeMap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B4G4R4A4 (Linear, A4R4G4B4).
        /// </summary>
        internal static string DdsFileFormat_B4G4R4A4 {
            get {
                return ResourceManager.GetString("DdsFileFormat_B4G4R4A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B5G5R5A1 (Linear, A1R5G5B5).
        /// </summary>
        internal static string DdsFileFormat_B5G5R5A1 {
            get {
                return ResourceManager.GetString("DdsFileFormat_B5G5R5A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B5G6R5 (Linear, R5G6B5).
        /// </summary>
        internal static string DdsFileFormat_B5G6R5 {
            get {
                return ResourceManager.GetString("DdsFileFormat_B5G6R5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B8G8R8 (Linear, R8G8B8).
        /// </summary>
        internal static string DdsFileFormat_B8G8R8 {
            get {
                return ResourceManager.GetString("DdsFileFormat_B8G8R8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B8G8R8A8 (Linear, A8R8G8B8).
        /// </summary>
        internal static string DdsFileFormat_B8G8R8A8 {
            get {
                return ResourceManager.GetString("DdsFileFormat_B8G8R8A8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B8G8R8A8 (sRGB, DX 10+).
        /// </summary>
        internal static string DdsFileFormat_B8G8R8A8Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_B8G8R8A8Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B8G8R8X8 (Linear, X8R8G8B8).
        /// </summary>
        internal static string DdsFileFormat_B8G8R8X8 {
            get {
                return ResourceManager.GetString("DdsFileFormat_B8G8R8X8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B8G8R8X8 (sRGB, DX 10+).
        /// </summary>
        internal static string DdsFileFormat_B8G8R8X8Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_B8G8R8X8Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC1 (Linear, DXT1).
        /// </summary>
        internal static string DdsFileFormat_BC1 {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC1 (sRGB, DX 10+).
        /// </summary>
        internal static string DdsFileFormat_BC1Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC1Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC2 (Linear, DXT3).
        /// </summary>
        internal static string DdsFileFormat_BC2 {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC2 (sRGB, DX 10+).
        /// </summary>
        internal static string DdsFileFormat_BC2Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC2Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC3 (Linear, DXT5).
        /// </summary>
        internal static string DdsFileFormat_BC3 {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC3 (sRGB, DX 10+).
        /// </summary>
        internal static string DdsFileFormat_BC3Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC3Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC4 (Linear, Unsigned).
        /// </summary>
        internal static string DdsFileFormat_BC4Unsigned {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC4Unsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC5 (Linear, Signed).
        /// </summary>
        internal static string DdsFileFormat_BC5Signed {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC5Signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC5 (Linear, Unsigned).
        /// </summary>
        internal static string DdsFileFormat_BC5Unsigned {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC5Unsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC6H (Linear, Unsigned, DX 11+).
        /// </summary>
        internal static string DdsFileFormat_BC6HUnsigned {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC6HUnsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC7 (Linear, DX 11+).
        /// </summary>
        internal static string DdsFileFormat_BC7 {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BC7 (sRGB, DX 11+).
        /// </summary>
        internal static string DdsFileFormat_BC7Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_BC7Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на R32 (Linear, Float).
        /// </summary>
        internal static string DdsFileFormat_R32Float {
            get {
                return ResourceManager.GetString("DdsFileFormat_R32Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на R8G8B8A8 (Linear, A8B8G8R8).
        /// </summary>
        internal static string DdsFileFormat_R8G8B8A8 {
            get {
                return ResourceManager.GetString("DdsFileFormat_R8G8B8A8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на R8G8B8A8 (sRGB, DX 10+).
        /// </summary>
        internal static string DdsFileFormat_R8G8B8A8Srgb {
            get {
                return ResourceManager.GetString("DdsFileFormat_R8G8B8A8Srgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на R8G8B8X8 (Linear, X8B8G8R8).
        /// </summary>
        internal static string DdsFileFormat_R8G8B8X8 {
            get {
                return ResourceManager.GetString("DdsFileFormat_R8G8B8X8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на R8G8 (Linear, Signed, V8U8).
        /// </summary>
        internal static string DdsFileFormat_R8G8Signed {
            get {
                return ResourceManager.GetString("DdsFileFormat_R8G8Signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на R8G8 (Linear, Unsigned, A8L8).
        /// </summary>
        internal static string DdsFileFormat_R8G8Unsigned {
            get {
                return ResourceManager.GetString("DdsFileFormat_R8G8Unsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на R8 (Linear, Unsigned, L8).
        /// </summary>
        internal static string DdsFileFormat_R8Unsigned {
            get {
                return ResourceManager.GetString("DdsFileFormat_R8Unsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error Metric.
        /// </summary>
        internal static string ErrorMetric_DisplayName {
            get {
                return ResourceManager.GetString("ErrorMetric_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Perceptual.
        /// </summary>
        internal static string ErrorMetric_Perceptual {
            get {
                return ResourceManager.GetString("ErrorMetric_Perceptual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uniform.
        /// </summary>
        internal static string ErrorMetric_Uniform {
            get {
                return ResourceManager.GetString("ErrorMetric_Uniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DirectDraw Surface (DDS).
        /// </summary>
        internal static string FileType_Name {
            get {
                return ResourceManager.GetString("FileType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forum Discussion.
        /// </summary>
        internal static string ForumLink_Description {
            get {
                return ResourceManager.GetString("ForumLink_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More Info.
        /// </summary>
        internal static string ForumLink_DisplayName {
            get {
                return ResourceManager.GetString("ForumLink_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate Mip Maps.
        /// </summary>
        internal static string GenerateMipMaps_Description {
            get {
                return ResourceManager.GetString("GenerateMipMaps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adaptive (Best Quality).
        /// </summary>
        internal static string ResamplingAlgorithm_AdaptiveBestQuality {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_AdaptiveBestQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bicubic.
        /// </summary>
        internal static string ResamplingAlgorithm_Cubic {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_Cubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fant.
        /// </summary>
        internal static string ResamplingAlgorithm_Fant {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_Fant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lanczos.
        /// </summary>
        internal static string ResamplingAlgorithm_Lanczos3 {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_Lanczos3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bilinear.
        /// </summary>
        internal static string ResamplingAlgorithm_Linear {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bilinear (Low Quality).
        /// </summary>
        internal static string ResamplingAlgorithm_LinearLowQuality {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_LinearLowQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nearest Neighbor.
        /// </summary>
        internal static string ResamplingAlgorithm_NearestNeighbor {
            get {
                return ResourceManager.GetString("ResamplingAlgorithm_NearestNeighbor", resourceCulture);
            }
        }
    }
}
